disUrl: https://b780e021-70dd-41f2-b320-c18a80b89fad.mock.pstmn.io/disService
validationUrl: https://b780e021-70dd-41f2-b320-c18a80b89fad.mock.pstmn.io/validation
spring:
  application:
    name: iesovsadapter
  config:
    import: configserver:http://config-server:8888
    enabled: true

Tenants_Configs:
  Tenant-1:
    validationRules:
      install:
        - validator_1
        - validator_2
        - validator_3
      remove:
        - validator_4
        - validator_5
    topics:
      tenant-1
  Tenant-2:
    validationRules:
      install:
        - validator_1
        - validator_3
      remove:
        validator_5
    topics:
      tenant-2